name: Oculus Documentation
markdown: kramdown
kramdown:
  input: GFM
  gfm_quirks: [paragraph_end, no_auto_typographic]
  html_to_native: true
  hard_wrap: false
  syntax_highlighter: rouge
  toc_levels: 2..3
incremental: true
permalink: pretty
safe: false
lsi: false
url: https://developer.oculus.com

defaults:
-
  scope:
    path: ""
    type: "pages"
  values:
    layout: docs
# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed
